"""Add questions_weekly_aggr table

Revision ID: 29edcfec6201
Revises: 37e132283f42
Create Date: 2026-02-13 22:43:11.149713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29edcfec6201'
down_revision: Union[str, Sequence[str], None] = '37e132283f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_weekly_aggr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_id', 'class_name', 'subject', 'date', name='uix_question_weekly_aggr')
    )
    with op.batch_alter_table('questions_weekly_aggr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_weekly_aggr_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_weekly_aggr_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_weekly_aggr_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_weekly_aggr_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_weekly_aggr_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_weekly_aggr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_weekly_aggr_user_id'))
        batch_op.drop_index(batch_op.f('ix_questions_weekly_aggr_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_weekly_aggr_profile_id'))
        batch_op.drop_index(batch_op.f('ix_questions_weekly_aggr_date'))
        batch_op.drop_index(batch_op.f('ix_questions_weekly_aggr_class_name'))

    op.drop_table('questions_weekly_aggr')
    # ### end Alembic commands ###
