"""Add feedback table

Revision ID: 37e132283f42
Revises: 5f26519e865e
Create Date: 2026-02-13 18:35:22.481567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '37e132283f42'
down_revision: Union[str, Sequence[str], None] = '5f26519e865e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('feedback_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'subject', 'created_at', name='uq_feedback_profile_subject_date')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_subject'), ['subject'], unique=False)

    with op.batch_alter_table('student_progress_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_progress_reports_id'))
        batch_op.drop_index(batch_op.f('ix_student_progress_reports_student_id'))

    op.drop_table('student_progress_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(), nullable=False),
    sa.Column('report_type', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_progress_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_progress_reports_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_progress_reports_id'), ['id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_subject'))
        batch_op.drop_index(batch_op.f('ix_feedback_profile_id'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
