"""initial_migration

Revision ID: 524684d25388
Revises: 
Create Date: 2026-01-29 12:24:08.184680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524684d25388'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_asked',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_asked_class_name'), 'questions_asked', ['class_name'], unique=False)
    op.create_index(op.f('ix_questions_asked_event_id'), 'questions_asked', ['event_id'], unique=True)
    op.create_index(op.f('ix_questions_asked_profile_id'), 'questions_asked', ['profile_id'], unique=False)
    op.create_index(op.f('ix_questions_asked_subject'), 'questions_asked', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_asked_user_id'), 'questions_asked', ['user_id'], unique=False)
    op.create_table('questions_asked_weekly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('no_of_questions', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'subject', 'week_start', name='uix_question_weekly')
    )
    op.create_index(op.f('ix_questions_asked_weekly_class_name'), 'questions_asked_weekly', ['class_name'], unique=False)
    op.create_index(op.f('ix_questions_asked_weekly_subject'), 'questions_asked_weekly', ['subject'], unique=False)
    op.create_table('test_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_papers_class_name'), 'test_papers', ['class_name'], unique=False)
    op.create_index(op.f('ix_test_papers_event_id'), 'test_papers', ['event_id'], unique=True)
    op.create_index(op.f('ix_test_papers_profile_id'), 'test_papers', ['profile_id'], unique=False)
    op.create_index(op.f('ix_test_papers_subject'), 'test_papers', ['subject'], unique=False)
    op.create_index(op.f('ix_test_papers_user_id'), 'test_papers', ['user_id'], unique=False)
    op.create_table('test_papers_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('no_of_tests', sa.Integer(), nullable=True),
    sa.Column('month_start', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'subject', 'month_start', name='uix_test_monthly')
    )
    op.create_index(op.f('ix_test_papers_monthly_class_name'), 'test_papers_monthly', ['class_name'], unique=False)
    op.create_index(op.f('ix_test_papers_monthly_subject'), 'test_papers_monthly', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_papers_monthly_subject'), table_name='test_papers_monthly')
    op.drop_index(op.f('ix_test_papers_monthly_class_name'), table_name='test_papers_monthly')
    op.drop_table('test_papers_monthly')
    op.drop_index(op.f('ix_test_papers_user_id'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_subject'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_profile_id'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_event_id'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_class_name'), table_name='test_papers')
    op.drop_table('test_papers')
    op.drop_index(op.f('ix_questions_asked_weekly_subject'), table_name='questions_asked_weekly')
    op.drop_index(op.f('ix_questions_asked_weekly_class_name'), table_name='questions_asked_weekly')
    op.drop_table('questions_asked_weekly')
    op.drop_index(op.f('ix_questions_asked_user_id'), table_name='questions_asked')
    op.drop_index(op.f('ix_questions_asked_subject'), table_name='questions_asked')
    op.drop_index(op.f('ix_questions_asked_profile_id'), table_name='questions_asked')
    op.drop_index(op.f('ix_questions_asked_event_id'), table_name='questions_asked')
    op.drop_index(op.f('ix_questions_asked_class_name'), table_name='questions_asked')
    op.drop_table('questions_asked')
    # ### end Alembic commands ###
