"""initial_schema

Revision ID: 5f26519e865e
Revises: 
Create Date: 2026-02-12 14:17:12.453435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f26519e865e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seconds_active', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject', 'date', name='uq_daily_activity_student_subject_date')
    )
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activity_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_subject'), ['subject'], unique=False)

    op.create_table('questions_asked',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions_asked', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_asked_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_asked_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_questions_asked_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_asked_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_asked_user_id'), ['user_id'], unique=False)

    op.create_table('questions_asked_weekly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('no_of_questions', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'subject', 'week_start', name='uix_question_weekly')
    )
    with op.batch_alter_table('questions_asked_weekly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_asked_weekly_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_asked_weekly_subject'), ['subject'], unique=False)

    op.create_table('test_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_papers_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_papers_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_test_papers_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_papers_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_papers_user_id'), ['user_id'], unique=False)

    op.create_table('test_papers_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('no_of_tests', sa.Integer(), nullable=True),
    sa.Column('month_start', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', 'subject', 'month_start', name='uix_test_monthly')
    )
    with op.batch_alter_table('test_papers_monthly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_papers_monthly_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_papers_monthly_subject'), ['subject'], unique=False)

    op.create_table('weekly_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('seconds_active', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject', 'week_start', name='uq_weekly_activity_student_subject_week')
    )
    with op.batch_alter_table('weekly_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_activity_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_activity_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_activity_subject'), ['subject'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_activity_subject'))
        batch_op.drop_index(batch_op.f('ix_weekly_activity_student_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_activity_id'))

    op.drop_table('weekly_activity')
    with op.batch_alter_table('test_papers_monthly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_papers_monthly_subject'))
        batch_op.drop_index(batch_op.f('ix_test_papers_monthly_class_name'))

    op.drop_table('test_papers_monthly')
    with op.batch_alter_table('test_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_papers_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_papers_subject'))
        batch_op.drop_index(batch_op.f('ix_test_papers_profile_id'))
        batch_op.drop_index(batch_op.f('ix_test_papers_event_id'))
        batch_op.drop_index(batch_op.f('ix_test_papers_class_name'))

    op.drop_table('test_papers')
    with op.batch_alter_table('questions_asked_weekly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_asked_weekly_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_asked_weekly_class_name'))

    op.drop_table('questions_asked_weekly')
    with op.batch_alter_table('questions_asked', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_asked_user_id'))
        batch_op.drop_index(batch_op.f('ix_questions_asked_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_asked_profile_id'))
        batch_op.drop_index(batch_op.f('ix_questions_asked_event_id'))
        batch_op.drop_index(batch_op.f('ix_questions_asked_class_name'))

    op.drop_table('questions_asked')
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activity_subject'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_student_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_date'))

    op.drop_table('daily_activity')
    # ### end Alembic commands ###
