"""Add subject activity

Revision ID: 662a4bdbf321
Revises: da1b0bcfc4b6
Create Date: 2026-02-12 13:31:04.859003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662a4bdbf321'
down_revision: Union[str, Sequence[str], None] = 'da1b0bcfc4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Daily Activity
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('subject', sa.String(), nullable=True)) # Already exists from previous run
        batch_op.drop_constraint('uq_daily_activity_student_date', type_='unique')
        batch_op.create_index(batch_op.f('ix_daily_activity_subject'), ['subject'], unique=False)
        batch_op.create_unique_constraint('uq_daily_activity_student_subject_date', ['student_id', 'subject', 'date'])

    # Weekly Activity
    with op.batch_alter_table('weekly_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.drop_constraint('uq_weekly_activity_student_week', type_='unique')
        batch_op.create_index(batch_op.f('ix_weekly_activity_subject'), ['subject'], unique=False)
        batch_op.create_unique_constraint('uq_weekly_activity_student_subject_week', ['student_id', 'subject', 'week_start'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weekly_activity_student_subject_week', 'weekly_activity', type_='unique')
    op.drop_index(op.f('ix_weekly_activity_subject'), table_name='weekly_activity')
    op.create_unique_constraint(op.f('uq_weekly_activity_student_week'), 'weekly_activity', ['student_id', 'week_start'])
    op.drop_column('weekly_activity', 'subject')
    op.drop_constraint('uq_daily_activity_student_subject_date', 'daily_activity', type_='unique')
    op.drop_index(op.f('ix_daily_activity_subject'), table_name='daily_activity')
    op.create_unique_constraint(op.f('uq_daily_activity_student_date'), 'daily_activity', ['student_id', 'date'])
    op.drop_column('daily_activity', 'subject')
    # ### end Alembic commands ###
