"""Add activity tables

Revision ID: da1b0bcfc4b6
Revises: 524684d25388
Create Date: 2026-02-12 10:27:11.957104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1b0bcfc4b6'
down_revision: Union[str, Sequence[str], None] = '524684d25388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seconds_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_daily_activity_student_date')
    )
    op.create_index(op.f('ix_daily_activity_date'), 'daily_activity', ['date'], unique=False)
    op.create_index(op.f('ix_daily_activity_id'), 'daily_activity', ['id'], unique=False)
    op.create_index(op.f('ix_daily_activity_student_id'), 'daily_activity', ['student_id'], unique=False)
    op.create_table('weekly_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('seconds_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'week_start', name='uq_weekly_activity_student_week')
    )
    op.create_index(op.f('ix_weekly_activity_id'), 'weekly_activity', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_activity_student_id'), 'weekly_activity', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_activity_student_id'), table_name='weekly_activity')
    op.drop_index(op.f('ix_weekly_activity_id'), table_name='weekly_activity')
    op.drop_table('weekly_activity')
    op.drop_index(op.f('ix_daily_activity_student_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_date'), table_name='daily_activity')
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
